apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-izur
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-izur@sha256:94d710deeb977d5c1d6649b8a7d0cd30c3782e38fe8b47b95bf6ca6aa786eec8
        name: my-nodejs
        resources: {}
status: {}
